In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")

df = pd.read_sql("SELECT * FROM Salaries", conn)

print("Rows and Columns:", df.shape)

df.head()

Rows and Columns: (148653, 13)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,

# Question 1:

 ## What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')

### Solution

In [4]:
query1 = """
SELECT 
    JobTitle,
    AVG(TotalPayBenefits) AS AverageTotalPayBenefits
FROM Salaries
WHERE JobTitle NOT IN ('Not Provided', 'Not provided')
GROUP BY JobTitle
ORDER BY AverageTotalPayBenefits DESC;
"""

q1 = pd.read_sql(query1, conn)
q1

                                            JobTitle  AverageTotalPayBenefits
0                           Chief Investment Officer            436224.360000
1                                    Chief of Police            411732.266667
2                             Chief, Fire Department            408865.326667
3     GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY            399211.275000
4                         Gen Mgr, Public Trnsp Dept            380696.440000
...                                              ...                      ...
2153                           SPECIAL ASSISTANT XIV               673.800000
2154              BOARD/COMMISSION MEMBER, GROUP III               638.787879
2155                      BdComm Mbr, Grp2,M=$25/Mtg               475.047742
2156               BOARD/COMMISSION MEMBER, GROUP II               296.511628
2157         PUBLIC SAFETY COMMUNICATIONS TECHNICIAN               149.510000

[2158 rows x 2 columns]

# Question 2

## Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000

### Solution

In [5]:
query2 = """
SELECT 
    JobTitle,
    OvertimePay
FROM Salaries
WHERE CAST(OvertimePay AS REAL) > 50000
ORDER BY CAST(OvertimePay AS REAL) DESC;
"""

q2 = pd.read_sql(query2, conn)
q2

                            JobTitle  OvertimePay
0       Lieutenant, Fire Suppression    220909.48
1                     Deputy Sheriff    196689.18
2          EMT/Paramedic/Firefighter    192424.49
3                     Deputy Sheriff    173547.73
4                     Deputy Sheriff    173178.23
...                              ...          ...
2159                Police Officer 3     50060.80
2160                      Sergeant 3     50055.88
2161  Battalion Chief, Fire Suppress     50039.97
2162                     FIREFIGHTER     50019.79
2163                     Firefighter     50018.08

[2164 rows x 2 columns]

# Question 3

## What is the total number of unique employees? exclude ('Not Provided', 'Not provided')

### Solution

In [6]:
query3 = """
SELECT 
    COUNT(DISTINCT EmployeeName) AS UniqueEmployees
FROM Salaries
WHERE EmployeeName NOT IN ('Not Provided', 'Not provided');
"""

q3 = pd.read_sql(query3, conn)
q3

   UniqueEmployees
0           110808

# Question 4

## Show The Top 10 highest Paid Employees

### Solution

In [7]:
query4 = """
SELECT 
    EmployeeName,
    JobTitle,
    TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
LIMIT 10;
"""

q4 = pd.read_sql(query4, conn)
q4

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

# Question 5

## Show All Employees Ordered By Their TotalPay Benefits In Descending Order

### Solution

In [8]:
query5 = """
SELECT 
    EmployeeName,
    JobTitle,
    TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC;
"""

q5 = pd.read_sql(query5, conn)
q5

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148648,Not provided,Not provided,0.00
148649,Timothy E Gibson,Police Officer 3,-2.73
148650,Mark E Laherty,Police Officer 3,-8.20
148651,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13