In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("factbook.db")

print("Database connected successfully!")

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table';",
    conn
)

print("\nAvailable Tables:")
display(tables)

Database connected successfully!

Available Tables:

              name
0  sqlite_sequence
1            facts
2           cities

# Question 1

## 1. List all cities where the area is greater than 5000, along with their population.

## Solution:

In [4]:
query = """
SELECT 
    c.name AS city_name,
    f.area,
    c.population
FROM cities c
JOIN facts f
    ON c.facts_id = f.id
WHERE f.area > 5000
ORDER BY c.name;
"""

result = pd.read_sql_query(query, conn)

result

                        city_name     area  population
0    ABIDJAN (seat of government)   322463     4288000
1                       Abu Dhabi    83600      942000
2                           Abuja   923768     2153000
3                           Accra   238533     2573000
4                       Ad Dammam  2149690      941000
..                            ...      ...         ...
349                       Yerevan    29743     1116000
350                        Zagreb    56594      686000
351                     Zamboanga   300000      884000
352                  Zaporizhzhya   603550      771000
353                        Zurich    41277     1194000

[354 rows x 3 columns]

# Question 2

## List the names of capital cities where the death rate is greater than 2% and the birth rate is less than 20%

## Solution

In [6]:
'''SELECT 
    c.name AS capital_city,
    f.death_rate,
    f.birth_rate
FROM cities c
JOIN facts f
    ON c.facts_id = f.id
WHERE c.capital = 1
  AND f.death_rate > 2
  AND f.birth_rate < 20
ORDER BY c.name;
'''

'SELECT \n    c.name AS capital_city,\n    f.death_rate,\n    f.birth_rate\nFROM cities c\nJOIN facts f\n    ON c.facts_id = f.id\nWHERE c.capital = 1\n  AND f.death_rate > 2\n  AND f.birth_rate < 20\nORDER BY c.name;\n'

# Question 3

## List the cities with a population growth rate between 1% and 5%, sorted in desc by population growth.

## Solution

In [7]:
"""
SELECT 
    c.name AS city_name,
    f.population_growth
FROM cities c
JOIN facts f
    ON c.facts_id = f.id
WHERE f.population_growth BETWEEN 1 AND 5
ORDER BY f.population_growth DESC;
"""

'\nSELECT \n    c.name AS city_name,\n    f.population_growth\nFROM cities c\nJOIN facts f\n    ON c.facts_id = f.id\nWHERE f.population_growth BETWEEN 1 AND 5\nORDER BY f.population_growth DESC;\n'

# Question 4

## Find countries that start with "A" and do not have any cities listed in the cities table. The query should return the country name and city name. Using left join

## Solution

In [9]:
"""
SELECT 
    f.name AS country_name,
    c.name AS city_name
FROM facts f
LEFT JOIN cities c
    ON f.id = c.facts_id
WHERE f.name LIKE 'A%'
  AND c.id IS NULL
ORDER BY f.name;
"""

"\nSELECT \n    f.name AS country_name,\n    c.name AS city_name\nFROM facts f\nLEFT JOIN cities c\n    ON f.id = c.facts_id\nWHERE f.name LIKE 'A%'\n  AND c.id IS NULL\nORDER BY f.name;\n"

# Question 5

## List all capital cities and their corresponding death rate using a LEFT JOIN.

## Solution

In [10]:
"""
SELECT 
    c.name AS capital_city,
    f.death_rate
FROM cities c
LEFT JOIN facts f
    ON c.facts_id = f.id
WHERE c.capital = 1
ORDER BY c.name;
"""

'\nSELECT \n    c.name AS capital_city,\n    f.death_rate\nFROM cities c\nLEFT JOIN facts f\n    ON c.facts_id = f.id\nWHERE c.capital = 1\nORDER BY c.name;\n'